project:
  type: website

execute:
  freeze: auto

website:
  site-url: https://kcsgoodboy.github.io/
  repo-url: https://github.com/kcsgoodboy/kcsgoodboy.github.io
  title: "Chan's Research Note"
  description: "A practitioner - scholar's research note on AI, Reinforcement Learning, and On-Device AI. Sharing insights from experiments, applications, and theories."
  page-navigation: true
  bread-crumbs: true
  open-graph:
    image: contents/images/persona.png
  twitter-card:
    image: contents/images/persona.png
    card-style: summary_large_image
  navbar:
    background: primary
    right: []
  google-analytics: "G-0JHM3R8BEZ"
  search:
    location: navbar
    type: overlay
    copy-button: true

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    css:  
      - assets/css/styles.css            
    toc: true
    comments:
      giscus:
        repo: kcsgoodboy/kcsgoodboy.github.io
        repo-id: R_kgDOPRiawA
        category: General
        category-id: DIC_kwDOPRiawM4CtfeS
        mapping: pathname
        reactions-enabled: true
        input-position: bottom
        language: en
    include-in-header: header.html

# babelquarto 설정
babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: ko
    text: "한국어"
  mainlanguage: en
  languages: ['ko']
title-ko: 생각많은 소심남의 연구노트
description-ko: 생각많은 소심남의 연구노트
author-ko: Chanseok Kang
lang: en
