website:
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: 소개
      - href: blog.qmd
        text: 블로그
      - href: publications.qmd
        text: 출간물
      - href: activities.qmd
        text: 활동