project:
  type: website

website:
  site-url: https://kcsgoodboy.github.io/
  repo-url: https://github.com/kcsgoodboy/kcsgoodboy.github.io
  title: "Chan's Research Note"
  page-navigation: true
  navbar:
    background: primary
    right: []

format:
  html:
    lib-dir: /site_libs
    theme:
      light: flatly
      dark:  darkly
    css:  
      - assets/css/styles.css            
    toc: true

# babelquarto 설정
babelquarto:
  languagecodes:
  - name: en
    text: "English"
  - name: ko
    text: "한국어"
  mainlanguage: en
  languages: ['ko']
title-ko: 생각많은 소심남의 연구노트
description-ko: 생각많은 소심남의 연구노트
author-ko: Chanseok Kang
lang: en
