website:
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: blog.qmd
      - href: publications.qmd
      - href: activities.qmd
lang: en
