project: 
  output-dir: docs

lang: ko

website:
  title: "생각많은 소심남의 노트"
  navbar:
    left:
      - href: index.qmd
        text: 홈
      - text: 소개
        href: about.qmd
      - text: 포스트
        href: posts/index.qmd
      - text: 출간물
        href: publications/index.qmd
    right:
      - text: "English"
        href: ./en/
      - icon: github
        href: https://github.com/goodboychan
      - icon: linkedin
        href: https://linkedin.com/in/chanseokk