website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
      - text: Posts
        href: posts/index.qmd # Assuming you'll create a posts directory with an index.qmd
      - text: Publications
        href: publications/index.qmd # Assuming you'll create a publications directory with an index.qmd
    right:
      - text: "한국어"
        href: /ko/
      - icon: github
        href: https://github.com/kcsgoodboy # REPLACE WITH YOUR GITHUB URL
      - icon: linkedin
        href: https://linkedin.com/in/yourprofile # REPLACE WITH YOUR LINKEDIN URL