project:
  type: website
  output-dir: _site

website:
  title: "Chans Lecture Note"
  google-analytics: "G-0JHM3R8BEZ"
  page-footer: "Copyright 2023, Chanseok Kang" 
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: publication/index.qmd
        text: Publication
      - text: Posts
        menu: 
          - text: English
            href: index.qmd
          - text: 한글
            href: posts/kr.qmd
    right:
      - href: https://github.com/goodboychan
        icon: github
      - href: https://www.linkedin.com/in/chanseokk/
        icon: linkedin

format:
  html:
    smooth-scroll: true
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

comments:
  giscus: 
    repo: kcsgoodboy/en