---
title: "활동"
description: "주요 활동, 컨퍼런스 발표 및 기술 기여 내역입니다."
lang: ko
date: '2026-04-17'
output: distill::distill_article
editor_options: 
  chunk_output_type: console
execute:
  echo: false
comments: false
---

```{r}
#| label: setup
#| include: false
library(distilltools)
```
## 2026

**(2026. 04)** 2026 IEEE 22nd CASE(International Conference on Automation Science and Engineering)의 Reviewer를 수행했습니다.
`r icon_link(text = "Link", url = "https://2026.ieeecase.org/")`

**(2026. 04)** 베타리더로 참여한 **"그림으로 배우는 생성형 AI"** (한빛미디어) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
실생활에서 생성형 AI 서비스를 사용하며 모델이 어떤 원리로 학습되고, 인간과 유사한 출력을 내는지 늘 궁금했습니다. 강의를 통해 공부해도 쉽게 이해되지 않는 부분이 있었는데, 이 책은 생성형 AI에 대한 기본지식이 있는 사람이라면 누구나 동작 원리와 예시를 이해할 수 있도록 도식과 설명이 잘 정리되어 있습니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219713793")`

**(2026. 04)** 베타리더로 참여한 **"그림으로 이해하는 AWS 구조와 기술 (2판)"** (길벗) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
TBD 
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219682418")`

**(2026. 04)** 베타리더로 참여한 **"개발자가 블로그도 잘 써야 하나요?"** (길벗) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
TBD 
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219662458")`

**(2026. 04)** 베타리더로 참여한 **"21개의 실무 앱으로 배우는 Dify"** (제이펍) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
TBD
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219647516")`

**(2026. 04)** 베타리더로 참여한 **"AI 자율학습 제미나이로 일 잘하는 법"** (길벗) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
우리 주변에는 유튜브나 안드로이드같이 구글에서 제공하는 서비스들이 일상속의 필수품처럼 자리잡아 있습니다. 특히 제미나이는 사용자가 원하는 다양한 작업을 처리해줄 수 있는 생성형 AI로써 많이 활용되고 있습니다. 이 책은 제미나이를 활용하여 아이데이션, 어떤 일을 수행하기전에 세우는 계획, 이미지생성, 학습과 같은 실생활 속에서 필요로 하는 다양한 업무에 접목시키는 내용을 쉽게 설명하고 있었습니다. 사실 저조차도 평소에 다양한 생성형AI 서비스를 나름대로 활용하고 있다고 생각했었지만, 이 책을 통해서도 제미나이가 제공하는 Gems나 Google Task에 연동하는 것과 같은 새로운 기능에 대해서 알 수 있어서 좋았습니다. 
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219506535")`

**(2026. 02)** 베타리더로 참여한 **"미니멀리즘 프로그래머"** (한빛미디어) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
단순함(simplicity)이란 컨셉트에 맞게 가벼운 분량으로 개발자가 가벼움을 고려하는 적절한 개발 습관에 대한 내용을 다루고 있습니다. 책을 읽으면서 저자의 의식에 몰입되는 경험을 하게 되었는데, 저자가 문제라고 언급하던 부분이 평소에는 제가 편의로 인해서 대충하던 일상이었던 것 같습니다. 그런 습관들을 해결하기 위해 여러 전략들을 저한테도 접목시킬 수 있다는 부분이 책을 통해서 얻을 수 있는 수확이 아니었을까 생각합니다. 복잡함을 추구하면서 개발하느라 복잡해진 머리를 이 책을 통해서 간결하게 만들 수 있으면 좋겠습니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219333716")`

**(2026. 02)** 베타리더로 참여한 **"AI 자율학습 클로드 코드·코덱스 CLI·제미나이 CLI 완전 활용법"** (길벗) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
생성형 AI가 발전하면서 다양한 모델과 도구가 출시되었고, 고품질의 소프트웨어를 비교적 쉽게 개발할 수 있는 환경이 마련되었습니다. 그런데 실무에서 이를 활용하려면 모델과 도구의 특징과 기능을 알고 목적에 따라 선택해야 합니다. 이 책에서는 대표적인 CLI 도구인 Claude Code, Codex CLI, Gemini CLI의 활용 방법을 쉽게 설명합니다. 설치 과정부터 각 도구가 제공하는 주요 기능까지 단계적으로 소개해 CLI 환경에서의 협업 개발 방식을 처음 접하는 개발자도 실무에 활용할 수 있습니다. 특히 CLI 환경에서 에이전트를 활용해 프로젝트르 개발하는 실전 방안을 다룬 부분이 매우 유용했습니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219080825")`


**(2026. 01)** 베타리더로 참여한 **"AI 에이전트 엔지니어링"** (한빛미디어) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
생성형 AI를 활용해 어플리케이션을 만드는 개발자에게는 실무적으로 접근할 수 있는 현실적인 책이라고 생각합니다. 관련 도메인의 빠른 발전에 따라 모델 성능뿐 아니라 고객과 에이전트 간 UI/UX 상호작용, 악용 사례 등을 사전에 고려한 보안 요소 등 간접적인 주제에 대한 논의도 활발해지고 있습니다. 이 책은 이러한 흐름 속에서 최신 학계의 방향성과 더불어 기업 실무에서 참고할 만한 방법론을 균형있게 제시하고 있어 의미가 큽니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000219002818")`


**(2026. 01)** 베타리더로 참여한 **"혼자서도 척척 해내는 AI 에이전트 만들기 with 랭체인&랭그래프"** (제이펍) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
LangChain과 LangSmith를 활용한 LLM과 주변 툴의 적용법, 더 나아가 LangGraph 기반의 에이전트 성능 관리 방법까지 소개합니다. 시중에도 책이 여러 권 나와 있지만, 이 책만의 차별점은 다양한 LLM 모델을 활용해 한국 독자에게 익숙한 종합부동산세법 사례를 직접 다룬다는 점으로, 활용 관점에서 더 현실적으로 와닿습니다.
:::


`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218961185")`

**(2026. 01)** 베타리더로 참여한 **"LUVIT 폴라스로 시작하는 데이터 분석"** (제이펍) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
데이터 분석시 많이 사용되는 Pandas를 대체해서 활용할 수 있는 Polars의 첫 책입니다. Polars 사용과 더불어 주어진 데이터셋에 대한 처리 방법과 시각화 기법도 소개하고 있어, 해당 툴을 사용해서 데이터 분석을 하려는 분들에게 도움이 될 것 같습니다.
:::


`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218938819")`

**(2026. 01)** 베타리더로 참여한 **"LLM을 위한 프롬프트 엔지니어링"** (제이펍) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
분량이 많은 편은 아니나, 실무에서 자주 접하는 핵심 주제들을 선별해 담으려 한 노력이 돋보입니다. 상세한 기술보다는 핵심 개념을 앞축적으로 설명해 기본적인 이해가 있는 독자들에게 특히 도움이 될 것 같습니다.
:::


`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218881475")`

## 2025
**(2025. 12)** 베타리더로 참여한 **"AI를 움직이는 수학 이야기"** (한빛미디어) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
인공지능 관련 업무를 수행하는데 수학적 소양이 반드시 필요한가에 대해서는 개개인의 의견이 다르겠지만, 근간을 이루는 기술을 깊이 이해할수록 학습자 스스로 수학적 소양에 대한 필요성을 느끼게 됩니다. 특히 다양한 분야에 적용되는 인공지능 기술의 성능을 개선하기 위해서는 그 원리를 구성하는 수학에 대한 이해 없이는 안 될 만큼 중요성이 더욱 커지고 있습니다.

이 책은 흔히 인공지능 전문서에서 다루는 코드 기반 설명이 아니라, 수식과 증명을 토대로 대표적인 알고리즘의 핵심 이론을 설명합니다. 처음에는 다소 어렵게 느껴질 수 있으나, 책에서 소개된 다양한 주제에 활용되는 수학적 이론을 직접 따라가며 읽다 보면, 어느덧 그 근간 기술의 원리를 자연스럽게 이해하고 있을 것입니다.
:::


`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218821406")`

**(2025. 12)** 베타리더로 참여한 **"프로그램을 읽는 기술"** (길벗) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
저도 그랬지만 대부분의 개발자들이 회사에 처음 입사해서 하는 일 중 하나는 선배들이 작성한 코드를 읽고 이해하는 일일 것입니다. 사실 남이 작성한 코드를 맨바닥부터 읽고 이해하기란 참 번거롭고 어려운 일이지만, 개발자의 개발 의도와 코드의 동작 흐름을 이해하기 위해서는 반드시 수행해야 할 과정이라고 생각합니다. 이 책에서는 짧은 분량 속에서도 코드를 읽는 방법과 실제 프로그램 속에서도 코드를 읽는 방법을 설명하며 프로그램의 동작 원리를 이해하는 실습을 해봅니다. 어떻게 보면 개인적으로도 가볍게 여길 법한 코드 읽는 방법에 대해서 다시 살펴보고 그 중요성에 대해서 환기할 수 있어서 좋았습니다. 또한 주제와 연관된 쉬운 예제를 부담 없이 읽으며 저자가 전달하고자 했던 의도를 이해할 수 있었습니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218795409")`

**(2025. 12)** 제가 베타리더로 참여한 **"한 번에 끝내는 라마인덱스 × RAG × AI 에이전트"** (제이펍) 책이 출간되었습니다.

::: {.callout-note title="Comment"}
RAG나 에이전트 구현을 처음 접하는 사람을 위해 LLM과 라마인덱스를 활용하는 내용을 단계적으로 제공합니다. 초반부에 이해에 필요한 이론적 배경을 곁들여 다양한 이해도를 가진 독자들을 충분히 커버할 수 있을 것이라 생각합니다. 무엇보다 후반부에 다뤄지는 LlamaParse를 활용한 멀티모달 에이전트 구현이나, gradio를 통해 LLM과 연계된 실제 챗봇을 구현해볼 수 있도록 구성한 점이 좋았습니다.
:::

`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218777354")`

**(2025. 12)** 제가 베타리더로 참여한 **"AI 자율학습 밑바닥부터 배우는 AI 에이전트"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218729898")`

**(2025. 11)** 제가 베타리더로 참여한 **"바이브 코딩 너머 개발자 생존법"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218400836")`

**(2025. 11)** 제가 베타리더로 참여한 **"그림으로 배우는 StatQuest 신경망 & AI 강의"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218314999")`

**(2025. 10)** 제가 베타리더로 참여한 **"라마인덱스로 배우는 데이터 기반 AI 애플리케이션"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218191644")`

**(2025. 10)** 제가 베타리더로 참여한 **"0과 1 사이"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218172019")`

**(2025. 10)** 제가 베타리더로 참여한 **"실무로 통하는 LLM 어플리케이션 설계"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218171872")`

**(2025. 10)** 제가 베타리더로 참여한 **"유니티 교과서"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000218148306")`

**(2025. 09)** 제가 베타리더로 참여한 **"AI 엔지니어링"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217939673")`

**(2025. 09)** 제가 베타리더로 참여한 **"AI 프로덕트 기획과 운영"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217939667")`

**(2025. 09)** 제가 베타리더로 참여한 **"할루시네이션을 줄여주는 프롬프트 엔지니어링"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217930344")`

**(2025. 09)** 제가 베타리더로 참여한 **"요즘 개발자를 위한 시스템 설계 수업"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217576068")`

**(2025. 09)** 제가 베타리더로 참여한 **"쏙쏙 들어오는 자료구조"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217555322")`

**(2025. 09)** 제가 베타리더로 참여한 **"LLM 프로덕션 엔지니어링"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217428546")`

**(2025. 08)** 제가 베타리더로 참여한 **"딥러닝 제대로 이해하기"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217252460")`

**(2025. 08)** 제가 베타리더로 참여한 **"(LUVIT) 커서로 시작하는 바이브 코딩"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000217127882")`

**(2025. 07)** 제가 베타리더로 참여한 **"깃허브 액션으로 구현하는 실전 CI/CD 설계와 운영"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216841015")`

**(2025. 06)** 제가 베타리더로 참여한 **"생성형 AI를 위한 프롬프트 엔지니어링"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216858506")`

**(2025. 06)** 제가 베타리더로 참여한 **"생성형 AI 활용 백과사전"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216842262")`

**(2025. 05)** 제가 베타리더로 참여한 **"잘되는 머신러닝 팀엔 이유가 있다"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216627633")`

**(2025. 05)** 제가 베타리더로 참여한 **"제미나이 인공지능 프로그래밍"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216405972")`

**(2025. 04)** 제가 베타리더로 참여한 **"모두의 딥러닝 (개정판 4판)"** (길벗) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216353566")`

**(2025. 04)** 제가 베타리더로 참여한 **"7가지 프로젝트로 배우는 LLM AI 에이전트 개발"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216210672")`

**(2025. 04)** 제가 베타리더로 참여한 **"조코딩의 AI 비트코인 자동 매매 시스템 만들기"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000216355639")`

**(2025. 03)** 제가 베타리더로 참여한 **"파이썬과 JAX로 추천 시스템 구축하기"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000215914781")`

**(2025. 03)** 제가 베타리더로 참여한 **"Azure OpenAI로 ChatGPT와 LLM 시스템 쉽고 빠르게 구축하기"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000215851003")`

**(2025. 02)** 제가 베타리더로 참여한 **"데이터 과학을 위한 소프트웨어 엔지니어링"** (제이펍) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000215709074")`

**(2025. 02)** 제가 베타리더로 참여한 **"그림으로 배우는 도커"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000215827785")`

**(2025. 01)** 제가 베타리더로 참여한 **"파이썬으로 웹 크롤러 만들기"** (한빛미디어) 책이 출간되었습니다.
`r icon_link(text = "Link", url = "https://product.kyobobook.co.kr/detail/S000215621325")`


## 2024

**(2024. 09)** 서울대학교 컴퓨터공학부 학생회에서 주최하는 ComSee 행사에서 **"실물 환경에서의 데이터 기반 강화학습 적용 방안"**이란 주제로 기업 강연 및 채용설명회를 진행했습니다.
`r icon_link(text = "File", url = "contents/files/AI_ComSee_RWRL.pdf")`

**(2024. 06)** 싱가포르에서 진행된 2024 [IEEE Conference on Artificial Intelligence (CAI)](https://ieeecai.org/)에서 **"Data-Driven Reinforcement Learning for Optimal Motor Control in Washing Machines"**이란 주제로 포스터 세션을 진행했습니다.

## 2023
**(2023. 02)** 제가 속한 팀에서 만든, 세계 최초로 Offline RL이 적용된 탈수 모델이 세탁기에 탑재되어 출시했습니다.
`r icon_link(text = "Press 1", url = "https://www.lge.co.kr/wash-combo/fh25lmth")`
`r icon_link(text = "Press 2", url = "https://live.lge.co.kr/2402-lg-signature/")`

## 2022

**(2022. 11)** LG전자에서 진행된 소프트웨어 개발자 컨퍼런스 (LG SDC)에서 **"실환경 데이터 기반 모델 성능 개선"**이란 주제로 발표를 진행했습니다.
`r icon_link(text = "Link", url = "https://live.lge.co.kr/2211-lg-sdc-2022-post/")`
`r icon_link(text = "File", url = "contents/files/T2_D1_Kang_DDRL.pdf")`

**(2022. 09)** 제가 번역한 **"그로킹 심층 강화학습"** (한빛미디어) 책이 2022년 대한민국학술원 우수학술도서로 선정되었습니다.
`r icon_link(text = "Link", url = "https://www.nas.go.kr/page/59725ab6-21c4-11ec-8e17-001e6746f4e8?searchGubun=N&page=1&reqst_dt=2022&book_lclas_cd_old=&book_lclas_cd=BOOK_LCLAS_04&search_type=&search_text=")`

## 2020

**(2020. 05)** [fastpages](https://fastpages.fast.ai/)를 활용하여, **"Chan's Jupyter"**란 기술 블로그를 운영하기 시작했습니다.
(해당 블로그에 있는 내용은 현재 블로그로 이전할 예정입니다.)
`r icon_link(text = "Link", url = "https://goodboychan.github.io/")`

## 2019

**(2019. 10)** LG전자에서 **인공지능 전문가(제어 분야)**로 선발되었습니다.
`r icon_link(text = "Press 1", url = "https://live.lge.co.kr/lg_ai_specialist_1020/")`
`r icon_link(text = "Press 2", url = "https://www.yna.co.kr/view/PYH20191020018800013")`

## 2010
**(2010. 08)** 티스토리에서 **자신에 대한 고찰** 이란 기술 블로그를 운영하기 시작했습니다.
`r icon_link(text = "Link", url = "https://talkingaboutme.tistory.com/")`