---
title: "Publications"
description: "A list of academic papers, books, and technical reviews"
lang: en
date: today
output: distill::distill_article
editor_options: 
  chunk_output_type: console
execute:
  echo: false
comments: false
---

```{r}
#| label: setup
#| include: false
library(distilltools)
```

`r icon_link("google-scholar", "Google Scholar", "https://scholar.google.com/citations?user=tyjigLkAAAAJ&hl=en")`

<!-- Manually add forthcoming pubs, e.g. 

## Forthcoming 

**Nitta, J. H.**, S. W. Laffan, B. D. Mishler, and W. Iwasaki. "canaper: Categorical analysis of neo- and paleo-endemism in R". In-press, *Ecography*.

`r icon_link(text = "Preprint", url = "https://www.biorxiv.org/content/10.1101/2022.10.06.511072v1")`
`r icon_link(icon = "github", text = "Code", url = "https://github.com/ropensci/canaper")` !-->
## 2026

Jinwoo Lee, **Chanseok Kang**, Guntae Bae. (2026) "Sensor-Based Reward Learning from Video Labels for Tumble Motion Control in a Household Dryer". To appear at 2026 IEEE 22nd International Conference on Automation Science and Engineering (CASE), August 2026.

`r icon_link(icon = "fas fa-link", text = "Project", url = "projects/reward-learning-dryer/", target = "_self")`

## 2024

**Chanseok Kang**, Guntae Bae, Daesung Kim, Kyoungwoo Lee, Dohyeon Son, Chul Lee, Jaeho Lee, Jinwoo Lee, Jae Woong Yun. (2024) "Data-Driven Reinforcement Learning for Optimal Motor Control in Washing Machines". 2024 IEEE Conference on Artificial Intelligence (CAI).

`r icon_link(icon = "fas fa-link", text = "Project", url = "projects/data-driven-rl-washing-machines/", target = "_self")`
`r icon_link(icon = "ieee", text = "IEEE", url = "https://ieeexplore.ieee.org/document/10605463/")`

**Chanseok Kang**. (2024) "Applying Data-Driven Reinforcement Learning Approach in Real World Environment". 2024 Journal of Institute of Electronics and Information Engineers (IEIE).

`r icon_link(text = "Preprint", url = "https://www.dbpia.co.kr/Journal/articleDetail?nodeId=NODE11799172")`

## 2021

**Chanseok Kang**. (2021) "Grokking Deep Reinforcement Learning" (Korean). Hanbit Media.

`r icon_link(icon = 'book', text = "Book", url = "https://www.hanbit.co.kr/store/books/look.php?p_code=B8984169041")`

## 2020

Changmin Ahn, Seungyul Lee, **Chanseok Kang**, Bernhard Egger. (2020) "NuPow: Managing Power on NUMA Multiprocessors with Domain-Level Voltage and Frequency Control".  International Conference on the Economics of Grids, Clouds, Systems, and Services. Cham: Springer International Publishing, 2020.

`r icon_link(icon = "springer", text = "Preprint", url = "https://link.springer.com/chapter/10.1007/978-3-030-63058-4_12")`

## 2019

Kyo-seok Song, **Chanseok Kang** (Reviewer). (2019) "Machine Learning with Tensorflow" (Korean). Hanbit Media.
`r icon_link(icon = 'book', text = "Book", url = "https://www.hanbit.co.kr/store/books/look.php?p_code=B8108682495")`

## 2017

**Chanseok Kang**, Seungyul Lee, Yong-Jun Lee, Jaejin Lee, Bernhard Egger. (2017) "Scheduling for Better Energy Efficiency on Many-Core Chips". Workshop on Job Scheduling Strategies for Parallel Processing. Cham: Springer International Publishing, 2015.

`r icon_link(icon = "springer", text = "Preprint", url = "https://link.springer.com/chapter/10.1007/978-3-319-61756-5_3")`
